export const API_URL = "http://localhost:8000/api/v1/company"

export const REQUEST_COMPANIES_PENDING = 'REQUEST_COMPANIES_PENDING';
export const REQUEST_COMPANIES_SUCCESS = 'REQUEST_COMPANIES_SUCCESS';
export const REQUEST_COMPANIES_FAILED = 'REQUEST_COMPANIES_FAILED';